
version: '3.5'

services:
  db:
    build:
      dockerfile: Dockerfile-db
      context: .
    ports:
      - "27021:27017"
    networks:
      - proxynet
    environment:
      MONGO_INITDB_DATABASE: mongo
  
  web:
    build: .
    command: /code/runserver.sh
    volumes:
      - .:/code
    ports:
      - "8004:8000"
    depends_on:
      - db
    networks:
      - proxynet
    environment:
      - COVERALLS_REPO_TOKEN
      - MONGO_USERNAME
      - MONGO_PASSWORD
      - MONGO_DB_NAME

  metabase:
    image: metabase/metabase
    ports:
      - "4000:3000"
    networks:
      - proxynet
    depends_on:
      - db

networks:
  proxynet:
    name: GamesBI-network