
version: '3.5'

services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: gamesbi
      POSTGRES_PASSWORD: gamesbi123
      POSTGRES_DB: gamesbi
      PGDATA: /tmp/pgdata
    networks:
      - proxynet
  
  web:
    build: .
    command: /code/runserver.sh
    volumes:
      - .:/code
    ports:
      - "8004:8000"
    depends_on:
      - db
    networks:
      - proxynet
    environment:
      - COVERALLS_REPO_TOKEN
      - MONGO_USERNAME
      - MONGO_PASSWORD
      - MONGO_DB_NAME
      - MB_USERNAME
      - MB_PASSWORD
      - DB_NAME

  metabase:
    image: metabase/metabase
    ports:
      - "4000:3000"
    networks:
      - proxynet
    depends_on:
      - db

networks:
  proxynet:
    name: GamesBI-network
